spring:
  application:
    name: data-scope
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/datainsight?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: InsightDataHikariCP
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  
  # Flyway配置
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
    placeholder-replacement: true
    placeholders:
      schema_name: datainsight
    table: flyway_schema_history
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    init-sql: CREATE DATABASE IF NOT EXISTS datainsight
    repair-on-migrate: true
    connect-retries: 3
    connect-retries-interval: 10
    mixed: false
    encoding: UTF-8

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.insightdata.infrastructure.persistence.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
  type-handlers-package: com.insightdata.infrastructure.persistence.typehandler

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

# 日志配置
logging:
  level:
    root: INFO
    com: INFO
    org.springframework: WARN
    org.flywaydb: DEBUG
  file:
    name: logs/insight-data.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用自定义配置
insight:
  # 数据源配置
  datasource:
    # 连接池配置
    connection-pool:
      default-max-size: 10
      default-min-idle: 2
      default-idle-timeout: 600000
      default-max-lifetime: 1800000
      default-connection-timeout: 30000
    
    # 元数据同步配置
    metadata-sync:
      default-timeout: 3600 # 默认同步超时时间（秒）
      max-concurrent-jobs: 3 # 最大并发同步任务数
      extraction-threads: 10 # 元数据提取线程数
  
  # 查询配置
  query:
    default-timeout: 30 # 默认查询超时时间（秒）
    max-timeout: 300 # 最大查询超时时间（秒）
    default-max-rows: 1000 # 默认最大返回行数
    max-rows-limit: 50000 # 最大行数限制
    max-concurrent-queries: 20 # 最大并发查询数
  
  # 缓存配置
  cache:
    metadata:
      expiration: 86400 # 元数据缓存过期时间（秒）
    query-result:
      expiration: 600 # 查询结果缓存过期时间（秒）
  
  # 安全配置
  security:
    jwt:
      secret: your-secret-key-here
      expiration: 86400 # Token过期时间（秒）
    encryption:
      algorithm: AES
      key-size: 256
      key-rotation-days: 90

# API文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.facade.rest