package com.insightdata.domain.metadata.model;

import com.insightdata.domain.metadata.enums.DataSourceType;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Data
public class DataSource {
    private String id;
    private String name;
    private DataSourceType type;
    private String host;
    private int port;
    private String databaseName;
    private String username;
    private String password;
    private String encryptedPassword;
    private String encryptionSalt;
    private boolean active;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime lastSyncTime;
    private Map<String, String> connectionProperties;
    private Set<String> tags;
    private Boolean enabled;
    private String description;
    private String driverClassName;
    private String jdbcUrl;

    // Getters and setters are automatically generated by Lombok's @Data annotation
}